export const rooms = [
    { id: 'M1', name: 'RoomM1', status: 'Available' },
    { id: 'A5', name: 'RoomA5', status: 'In Use' },
    { id: 'B2', name: 'RoomB2', status: 'Available' },
    { id: 'C3', name: 'RoomC3', status: 'In Use' }
  ];
 export const M1_Students = [
  { id: 'M1-S1', name: 'Logan Scott', roomtype: 'M1', age: 20, gender: 'Male', image: 'https://randomuser.me/api/portraits/men/21.jpg' },
  { id: 'M1-S2', name: 'Amelia Walker', roomtype: 'M1', age: 22, gender: 'Female', image: 'https://randomuser.me/api/portraits/women/21.jpg' },
  { id: 'M1-S3', name: 'Mason Young', roomtype: 'M1', age: 21, gender: 'Male', image: 'https://randomuser.me/api/portraits/men/23.jpg' },
  { id: 'M1-S4', name: 'Harper Allen', roomtype: 'M1', age: 23, gender: 'Female', image: 'https://randomuser.me/api/portraits/women/23.jpg' },
  { id: 'M1-S5', name: 'Ethan King', roomtype: 'M1', age: 22, gender: 'Male', image: 'https://randomuser.me/api/portraits/men/24.jpg' },
  { id: 'M1-S6', name: 'Abigail Wright', roomtype: 'M1', age: 19, gender: 'Female', image: 'https://randomuser.me/api/portraits/women/24.jpg' },
  { id: 'M1-S7', name: 'Daniel Lopez', roomtype: 'M1', age: 18, gender: 'Male', image: 'https://randomuser.me/api/portraits/men/25.jpg' },
  { id: 'M1-S8', name: 'Emily Hill', roomtype: 'M1', age: 21, gender: 'Female', image: 'https://randomuser.me/api/portraits/women/25.jpg' },
  { id: 'M1-S9', name: 'Matthew Green', roomtype: 'M1', age: 22, gender: 'Male', image: 'https://randomuser.me/api/portraits/men/26.jpg' },
  { id: 'M1-S10', name: 'Elizabeth Adams', roomtype: 'M1', age: 20, gender: 'Female', image: 'https://randomuser.me/api/portraits/women/26.jpg' },
  { id: 'M1-S11', name: 'David Nelson', roomtype: 'M1', age: 19, gender: 'Male', image: 'https://randomuser.me/api/portraits/men/27.jpg' },
  { id: 'M1-S12', name: 'Sofia Baker', roomtype: 'M1', age: 18, gender: 'Female', image: 'https://randomuser.me/api/portraits/women/27.jpg' },
  { id: 'M1-S13', name: 'Joseph Carter', roomtype: 'M1', age: 21, gender: 'Male', image: 'https://randomuser.me/api/portraits/men/28.jpg' },
  { id: 'M1-S14', name: 'Avery Mitchell', roomtype: 'M1', age: 22, gender: 'Female', image: 'https://randomuser.me/api/portraits/women/28.jpg' },
  { id: 'M1-S15', name: 'Samuel Perez', roomtype: 'M1', age: 23, gender: 'Male', image: 'https://randomuser.me/api/portraits/men/29.jpg' },
  { id: 'M1-S16', name: 'Ella Roberts', roomtype: 'M1', age: 20, gender: 'Female', image: 'https://randomuser.me/api/portraits/women/29.jpg' },
  { id: 'M1-S17', name: 'Jackson Turner', roomtype: 'M1', age: 19, gender: 'Male', image: 'https://randomuser.me/api/portraits/men/30.jpg' },
  { id: 'M1-S18', name: 'Chloe Phillips', roomtype: 'M1', age: 21, gender: 'Female', image: 'https://randomuser.me/api/portraits/women/30.jpg' },
  { id: 'M1-S19', name: 'Luke Campbell', roomtype: 'M1', age: 20, gender: 'Male', image: 'https://randomuser.me/api/portraits/men/31.jpg' },
  { id: 'M1-S20', name: 'Victoria Parker', roomtype: 'M1', age: 22, gender: 'Female', image: 'https://randomuser.me/api/portraits/women/31.jpg' },
  { id: 'M1-S21', name: 'Jack Evans', roomtype: 'M1', age: 23, gender: 'Male', image: 'https://randomuser.me/api/portraits/men/32.jpg' },
  { id: 'M1-S22', name: 'Grace Edwards', roomtype: 'M1', age: 18, gender: 'Female', image: 'https://randomuser.me/api/portraits/women/32.jpg' },
  { id: 'M1-S23', name: 'Owen Collins', roomtype: 'M1', age: 19, gender: 'Male', image: 'https://randomuser.me/api/portraits/men/33.jpg' },
  { id: 'M1-S24', name: 'Zoey Stewart', roomtype: 'M1', age: 20, gender: 'Female', image: 'https://randomuser.me/api/portraits/women/33.jpg' },
  { id: 'M1-S25', name: 'Nathan Sanchez', roomtype: 'M1', age: 21, gender: 'Male', image: 'https://randomuser.me/api/portraits/men/34.jpg' },
  { id: 'M1-S26', name: 'Lillian Morris', roomtype: 'M1', age: 22, gender: 'Female', image: 'https://randomuser.me/api/portraits/women/34.jpg' },
  { id: 'M1-S27', name: 'Christian Rogers', roomtype: 'M1', age: 23, gender: 'Male', image: 'https://randomuser.me/api/portraits/men/35.jpg' },
  { id: 'M1-S28', name: 'Natalie Reed', roomtype: 'M1', age: 21, gender: 'Female', image: 'https://randomuser.me/api/portraits/women/35.jpg' },
  { id: 'M1-S29', name: 'Isaiah Cook', roomtype: 'M1', age: 20, gender: 'Male', image: 'https://randomuser.me/api/portraits/men/36.jpg' },
  { id: 'M1-S30', name: 'Hannah Morgan', roomtype: 'M1', age: 18, gender: 'Female', image: 'https://randomuser.me/api/portraits/women/36.jpg' },
];


export const A5_Students = [
  { id: 'A5-S1', name: 'Liam Davis', age: 20, gender: 'Male', roomtype: 'A5', image: 'https://randomuser.me/api/portraits/men/81.jpg' },
  { id: 'A5-S2', name: 'Olivia Martinez', age: 21, gender: 'Female', roomtype: 'A5', image: 'https://randomuser.me/api/portraits/women/81.jpg' },
  { id: 'A5-S3', name: 'Noah Wilson', age: 22, gender: 'Male', roomtype: 'A5', image: 'https://randomuser.me/api/portraits/men/82.jpg' },
  { id: 'A5-S4', name: 'Emma Anderson', age: 19, gender: 'Female', roomtype: 'A5', image: 'https://randomuser.me/api/portraits/women/82.jpg' },
  { id: 'A5-S5', name: 'Ethan Thomas', age: 23, gender: 'Male', roomtype: 'A5', image: 'https://randomuser.me/api/portraits/men/83.jpg' },
  { id: 'A5-S6', name: 'Ava Jackson', age: 20, gender: 'Female', roomtype: 'A5', image: 'https://randomuser.me/api/portraits/women/83.jpg' },
  { id: 'A5-S7', name: 'James White', age: 21, gender: 'Male', roomtype: 'A5', image: 'https://randomuser.me/api/portraits/men/84.jpg' },
  { id: 'A5-S8', name: 'Sophia Harris', age: 22, gender: 'Female', roomtype: 'A5', image: 'https://randomuser.me/api/portraits/women/84.jpg' },
  { id: 'A5-S9', name: 'Benjamin Martin', age: 18, gender: 'Male', roomtype: 'A5', image: 'https://randomuser.me/api/portraits/men/85.jpg' },
  { id: 'A5-S10', name: 'Isabella Thompson', age: 19, gender: 'Female', roomtype: 'A5', image: 'https://randomuser.me/api/portraits/women/85.jpg' },
  { id: 'A5-S11', name: 'Lucas Garcia', age: 20, gender: 'Male', roomtype: 'A5', image: 'https://randomuser.me/api/portraits/men/86.jpg' },
  { id: 'A5-S12', name: 'Mia Martinez', age: 21, gender: 'Female', roomtype: 'A5', image: 'https://randomuser.me/api/portraits/women/86.jpg' },
  { id: 'A5-S13', name: 'Logan Lee', age: 22, gender: 'Male', roomtype: 'A5', image: 'https://randomuser.me/api/portraits/men/87.jpg' },
  { id: 'A5-S14', name: 'Charlotte Walker', age: 23, gender: 'Female', roomtype: 'A5', image: 'https://randomuser.me/api/portraits/women/87.jpg' },
  { id: 'A5-S15', name: 'Daniel Young', age: 19, gender: 'Male', roomtype: 'A5', image: 'https://randomuser.me/api/portraits/men/88.jpg' },
  { id: 'A5-S16', name: 'Amelia Hall', age: 18, gender: 'Female', roomtype: 'A5', image: 'https://randomuser.me/api/portraits/women/88.jpg' },
  { id: 'A5-S17', name: 'Matthew Allen', age: 21, gender: 'Male', roomtype: 'A5', image: 'https://randomuser.me/api/portraits/men/89.jpg' },
  { id: 'A5-S18', name: 'Harper Wright', age: 20, gender: 'Female', roomtype: 'A5', image: 'https://randomuser.me/api/portraits/women/89.jpg' },
  { id: 'A5-S19', name: 'Jacob Scott', age: 22, gender: 'Male', roomtype: 'A5', image: 'https://randomuser.me/api/portraits/men/90.jpg' },
  { id: 'A5-S20', name: 'Ella Green', age: 19, gender: 'Female', roomtype: 'A5', image: 'https://randomuser.me/api/portraits/women/90.jpg' },
];

export const B2_Students = [
  { id: 'B2-S1', name: 'Aiden Rivera', age: 21, gender: 'Male', roomtype: 'B2', image: 'https://randomuser.me/api/portraits/men/91.jpg' },
  { id: 'B2-S2', name: 'Aria Jenkins', age: 20, gender: 'Female', roomtype: 'B2', image: 'https://randomuser.me/api/portraits/women/91.jpg' },
  { id: 'B2-S3', name: 'Jackson Perry', age: 19, gender: 'Male', roomtype: 'B2', image: 'https://randomuser.me/api/portraits/men/92.jpg' },
  { id: 'B2-S4', name: 'Scarlett Ford', age: 22, gender: 'Female', roomtype: 'B2', image: 'https://randomuser.me/api/portraits/women/92.jpg' },
  { id: 'B2-S5', name: 'Henry Bennett', age: 20, gender: 'Male', roomtype: 'B2', image: 'https://randomuser.me/api/portraits/men/93.jpg' },
  { id: 'B2-S6', name: 'Grace Murphy', age: 23, gender: 'Female', roomtype: 'B2', image: 'https://randomuser.me/api/portraits/women/93.jpg' },
  { id: 'B2-S7', name: 'Sebastian Cox', age: 18, gender: 'Male', roomtype: 'B2', image: 'https://randomuser.me/api/portraits/men/94.jpg' },
  { id: 'B2-S8', name: 'Chloe Ortiz', age: 19, gender: 'Female', roomtype: 'B2', image: 'https://randomuser.me/api/portraits/women/94.jpg' },
  { id: 'B2-S9', name: 'Wyatt Simmons', age: 22, gender: 'Male', roomtype: 'B2', image: 'https://randomuser.me/api/portraits/men/95.jpg' },
  { id: 'B2-S10', name: 'Lily Ramirez', age: 20, gender: 'Female', roomtype: 'B2', image: 'https://randomuser.me/api/portraits/women/95.jpg' },
  { id: 'B2-S11', name: 'Owen Mitchell', age: 21, gender: 'Male', roomtype: 'B2', image: 'https://randomuser.me/api/portraits/men/96.jpg' },
  { id: 'B2-S12', name: 'Zoe Bailey', age: 18, gender: 'Female', roomtype: 'B2', image: 'https://randomuser.me/api/portraits/women/96.jpg' },
  { id: 'B2-S13', name: 'Levi Kelly', age: 19, gender: 'Male', roomtype: 'B2', image: 'https://randomuser.me/api/portraits/men/97.jpg' },
  { id: 'B2-S14', name: 'Nora Price', age: 23, gender: 'Female', roomtype: 'B2', image: 'https://randomuser.me/api/portraits/women/97.jpg' },
  { id: 'B2-S15', name: 'Julian Barnes', age: 20, gender: 'Male', roomtype: 'B2', image: 'https://randomuser.me/api/portraits/men/98.jpg' },
  { id: 'B2-S16', name: 'Ellie Ross', age: 21, gender: 'Female', roomtype: 'B2', image: 'https://randomuser.me/api/portraits/women/98.jpg' },
  { id: 'B2-S17', name: 'Gabriel Powell', age: 18, gender: 'Male', roomtype: 'B2', image: 'https://randomuser.me/api/portraits/men/99.jpg' },
  { id: 'B2-S18', name: 'Hazel Russell', age: 22, gender: 'Female', roomtype: 'B2', image: 'https://randomuser.me/api/portraits/women/99.jpg' },
  { id: 'B2-S19', name: 'Carter Torres', age: 23, gender: 'Male', roomtype: 'B2', image: 'https://randomuser.me/api/portraits/men/100.jpg' },
  { id: 'B2-S20', name: 'Victoria Peterson', age: 19, gender: 'Female', roomtype: 'B2', image: 'https://randomuser.me/api/portraits/women/100.jpg' },
  { id: 'B2-S21', name: 'Nathan Gray', age: 21, gender: 'Male', roomtype: 'B2', image: 'https://randomuser.me/api/portraits/men/101.jpg' },
  { id: 'B2-S22', name: 'Aubrey James', age: 20, gender: 'Female', roomtype: 'B2', image: 'https://randomuser.me/api/portraits/women/101.jpg' },
  { id: 'B2-S23', name: 'Aaron Watson', age: 18, gender: 'Male', roomtype: 'B2', image: 'https://randomuser.me/api/portraits/men/102.jpg' },
  { id: 'B2-S24', name: 'Brooklyn Brooks', age: 22, gender: 'Female', roomtype: 'B2', image: 'https://randomuser.me/api/portraits/women/102.jpg' },
  { id: 'B2-S25', name: 'Elijah Sanders', age: 19, gender: 'Male', roomtype: 'B2', image: 'https://randomuser.me/api/portraits/men/103.jpg' },
  { id: 'B2-S26', name: 'Stella Long', age: 23, gender: 'Female', roomtype: 'B2', image: 'https://randomuser.me/api/portraits/women/103.jpg' },
  { id: 'B2-S27', name: 'Isaac Patterson', age: 20, gender: 'Male', roomtype: 'B2', image: 'https://randomuser.me/api/portraits/men/104.jpg' },
  { id: 'B2-S28', name: 'Riley Hughes', age: 21, gender: 'Female', roomtype: 'B2', image: 'https://randomuser.me/api/portraits/women/104.jpg' },
  { id: 'B2-S29', name: 'Anthony Flores', age: 22, gender: 'Male', roomtype: 'B2', image: 'https://randomuser.me/api/portraits/men/105.jpg' },
  { id: 'B2-S30', name: 'Penelope Ward', age: 18, gender: 'Female', roomtype: 'B2', image: 'https://randomuser.me/api/portraits/women/105.jpg' },
];

  
  
  export const C3_Students = [
  { id: 'C3-S1', name: 'Julian Sanders', age: 19, gender: 'Male', image: 'https://randomuser.me/api/portraits/men/29.jpg', roomtype: 'C3' },
  { id: 'C3-S2', name: 'Natalie Price', age: 21, gender: 'Female', image: 'https://randomuser.me/api/portraits/women/43.jpg', roomtype: 'C3' },
  { id: 'C3-S3', name: 'Isaac Bennett', age: 22, gender: 'Male', image: 'https://randomuser.me/api/portraits/men/30.jpg', roomtype: 'C3' },
  { id: 'C3-S4', name: 'Layla Long', age: 20, gender: 'Female', image: 'https://randomuser.me/api/portraits/women/44.jpg', roomtype: 'C3' },
  { id: 'C3-S5', name: 'Levi Russell', age: 20, gender: 'Male', image: 'https://randomuser.me/api/portraits/men/31.jpg', roomtype: 'C3' },
  { id: 'C3-S6', name: 'Aubrey Griffin', age: 18, gender: 'Female', image: 'https://randomuser.me/api/portraits/women/45.jpg', roomtype: 'C3' },
  { id: 'C3-S7', name: 'Hudson Diaz', age: 21, gender: 'Male', image: 'https://randomuser.me/api/portraits/men/32.jpg', roomtype: 'C3' },
  { id: 'C3-S8', name: 'Sofia Hayes', age: 22, gender: 'Female', image: 'https://randomuser.me/api/portraits/women/46.jpg', roomtype: 'C3' },
  { id: 'C3-S9', name: 'Dylan Jenkins', age: 19, gender: 'Male', image: 'https://randomuser.me/api/portraits/men/33.jpg', roomtype: 'C3' },
  { id: 'C3-S10', name: 'Victoria Perry', age: 20, gender: 'Female', image: 'https://randomuser.me/api/portraits/women/47.jpg', roomtype: 'C3' },
  { id: 'C3-S11', name: 'Nathan Powell', age: 21, gender: 'Male', image: 'https://randomuser.me/api/portraits/men/34.jpg', roomtype: 'C3' },
  { id: 'C3-S12', name: 'Ellie Patterson', age: 19, gender: 'Female', image: 'https://randomuser.me/api/portraits/women/48.jpg', roomtype: 'C3' },
  { id: 'C3-S13', name: 'Christian Hughes', age: 22, gender: 'Male', image: 'https://randomuser.me/api/portraits/men/35.jpg', roomtype: 'C3' },
  { id: 'C3-S14', name: 'Aria Flores', age: 18, gender: 'Female', image: 'https://randomuser.me/api/portraits/women/49.jpg', roomtype: 'C3' },
  { id: 'C3-S15', name: 'Andrew Washington', age: 20, gender: 'Male', image: 'https://randomuser.me/api/portraits/men/36.jpg', roomtype: 'C3' },
  { id: 'C3-S16', name: 'Gabriel Freeman', age: 20, gender: 'Male', image: 'https://randomuser.me/api/portraits/men/37.jpg', roomtype: 'C3' },
  { id: 'C3-S17', name: 'Scarlett Bishop', age: 21, gender: 'Female', image: 'https://randomuser.me/api/portraits/women/50.jpg', roomtype: 'C3' },
  { id: 'C3-S18', name: 'Eli Coleman', age: 22, gender: 'Male', image: 'https://randomuser.me/api/portraits/men/38.jpg', roomtype: 'C3' },
  { id: 'C3-S19', name: 'Paisley Howard', age: 19, gender: 'Female', image: 'https://randomuser.me/api/portraits/women/51.jpg', roomtype: 'C3' },
  { id: 'C3-S20', name: 'Caleb Ward', age: 23, gender: 'Male', image: 'https://randomuser.me/api/portraits/men/39.jpg', roomtype: 'C3' },
  { id: 'C3-S21', name: 'Aurora Cox', age: 20, gender: 'Female', image: 'https://randomuser.me/api/portraits/women/52.jpg', roomtype: 'C3' },
  { id: 'C3-S22', name: 'Aaron Rivera', age: 21, gender: 'Male', image: 'https://randomuser.me/api/portraits/men/40.jpg', roomtype: 'C3' },
  { id: 'C3-S23', name: 'Stella Bryant', age: 18, gender: 'Female', image: 'https://randomuser.me/api/portraits/women/53.jpg', roomtype: 'C3' },
  { id: 'C3-S24', name: 'Landon Alexander', age: 20, gender: 'Male', image: 'https://randomuser.me/api/portraits/men/41.jpg', roomtype: 'C3' },
  { id: 'C3-S25', name: 'Savannah Graham', age: 22, gender: 'Female', image: 'https://randomuser.me/api/portraits/women/54.jpg', roomtype: 'C3' },
  { id: 'C3-S26', name: 'Xavier Stone', age: 19, gender: 'Male', image: 'https://randomuser.me/api/portraits/men/42.jpg', roomtype: 'C3' },
  { id: 'C3-S27', name: 'Brooklyn Weaver', age: 21, gender: 'Female', image: 'https://randomuser.me/api/portraits/women/55.jpg', roomtype: 'C3' },
  { id: 'C3-S28', name: 'Hunter Chambers', age: 20, gender: 'Male', image: 'https://randomuser.me/api/portraits/men/43.jpg', roomtype: 'C3' },
  { id: 'C3-S29', name: 'Nora Matthews', age: 18, gender: 'Female', image: 'https://randomuser.me/api/portraits/women/56.jpg', roomtype: 'C3' },
  { id: 'C3-S30', name: 'Thomas Barrett', age: 23, gender: 'Male', image: 'https://randomuser.me/api/portraits/men/44.jpg', roomtype: 'C3' },
];

  


  
  